require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/experiences", type: :request do

  before(:each) do
    @user = User.create!(email: "test@testing.net", password: "123456")
    sign_in(@user)
  end
  
  # This should return the minimal set of attributes required to create a valid
  # Experience. As you add validations to Experience, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      company: "Some Company Name",
      position: "Engineer",
      description: "Cool description",
      start_date: 1.year.ago.to_date,
      end_date: Date.current,
      company_url: "www.google.com",
      company_logo: fixture_file_upload(Rails.root.join('spec', 'fixtures', 'images', 'logo.png'))
    }
  }

  let(:invalid_attributes) {
    {
      company: "",
      position: "Engineer",
      description: "Cool description",
      start_date: nil,
      end_date: Date.current
    }
  }

  describe "GET /new" do
    it "renders a successful response" do
      get new_experience_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      experience = Experience.create! valid_attributes
      get edit_experience_url(experience)
      expect(response).to be_successful
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested experience" do
      experience = Experience.create! valid_attributes
      expect {
        delete experience_url(experience)
      }.to change(Experience, :count).by(-1)
    end
  end
end
